//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Internacionalizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormaGeometrica {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormaGeometrica() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Internacionalizacion.FormaGeometrica", typeof(FormaGeometrica).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circles.
        /// </summary>
        internal static string CirculoPlural {
            get {
                return ResourceManager.GetString("CirculoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circle.
        /// </summary>
        internal static string CirculoSingular {
            get {
                return ResourceManager.GetString("CirculoSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Squares.
        /// </summary>
        internal static string CuadradoPlural {
            get {
                return ResourceManager.GetString("CuadradoPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Square.
        /// </summary>
        internal static string CuadradoSingular {
            get {
                return ResourceManager.GetString("CuadradoSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectangles.
        /// </summary>
        internal static string RectanguloPlural {
            get {
                return ResourceManager.GetString("RectanguloPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectangle.
        /// </summary>
        internal static string RectanguloSingular {
            get {
                return ResourceManager.GetString("RectanguloSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shapes.
        /// </summary>
        internal static string ReporteFormas {
            get {
                return ResourceManager.GetString("ReporteFormas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Empty list of shapes!&lt;/h1&gt;.
        /// </summary>
        internal static string ReporteListaVacia {
            get {
                return ResourceManager.GetString("ReporteListaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimeter.
        /// </summary>
        internal static string ReportePerimetro {
            get {
                return ResourceManager.GetString("ReportePerimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;h1&gt;Shapes report&lt;/h1&gt;.
        /// </summary>
        internal static string ReporteTitulo {
            get {
                return ResourceManager.GetString("ReporteTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapezes.
        /// </summary>
        internal static string TrapecioPlural {
            get {
                return ResourceManager.GetString("TrapecioPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapeze.
        /// </summary>
        internal static string TrapecioSingular {
            get {
                return ResourceManager.GetString("TrapecioSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangles.
        /// </summary>
        internal static string TrianguloPlural {
            get {
                return ResourceManager.GetString("TrianguloPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangle.
        /// </summary>
        internal static string TrianguloSingular {
            get {
                return ResourceManager.GetString("TrianguloSingular", resourceCulture);
            }
        }
    }
}
